package com.fyp.blockchainhealthwallet.zkp

import android.annotation.SuppressLint
import android.app.Activity
import android.content.Context
import android.util.Log
import android.view.ViewGroup
import android.webkit.ConsoleMessage
import android.webkit.JavascriptInterface
import android.webkit.WebChromeClient
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.webkit.WebViewAssetLoader
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withTimeout
import org.json.JSONArray
import org.json.JSONObject
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

/**
 * ZkpService
 *
 * Generates a Groth16 ZK proof that the user is 18+ WITHOUT revealing their birth year.
 *
 * Internally spins up a hidden WebView that loads snarkjs_wrapper.html which runs snarkjs WASM.
 * The birth year is passed to JavaScript only — it never touches any network or storage.
 * Only the finished proof (3 elliptic curve points + public signals) is returned.
 *
 * Circuit files required in app/src/main/assets/zkp/:
 *   - snarkjs_wrapper.html
 *   - AgeVerify.wasm         (generated by setupCircuit.js)
 *   - AgeVerify_final.zkey   (generated by setupCircuit.js)
 */
class ZkpService(private val activity: Activity) {

    private val context: Context get() = activity

    companion object {
        private const val TAG = "ZkpService"
        private const val PROOF_TIMEOUT_MS = 60_000L  // 60s — includes snarkjs WASM init on first run
    }

    private var webView: WebView? = null
    private var proofCallback: ((Result<ZkpProofResult>) -> Unit)? = null
    private var vaccineProofCallback: ((Result<VaccineZkpProofResult>) -> Unit)? = null
    private var poseidonCallback: ((Result<String>) -> Unit)? = null
    private var engineReady = false

    // -------------------------------------------------------
    // Public API
    // -------------------------------------------------------

    /**
     * Generate an age proof.
     * Must be called from the MAIN THREAD (WebView requirement).
     *
     * @param birthYear  User's birth year  (e.g. 1995). STAYS ON DEVICE.
     * @param birthMonth User's birth month (1-12).     STAYS ON DEVICE.
     * @param birthDay   User's birth day   (1-31).     STAYS ON DEVICE.
     * @return ZkpProofResult — proof + public signals (no birth date)
     */
    @SuppressLint("SetJavaScriptEnabled")
    suspend fun generateAgeProof(birthYear: Int, birthMonth: Int, birthDay: Int): ZkpProofResult {
        val cal = java.util.Calendar.getInstance()
        val currentYear  = cal.get(java.util.Calendar.YEAR)
        val currentMonth = cal.get(java.util.Calendar.MONTH) + 1   // Calendar.MONTH is 0-based
        val currentDay   = cal.get(java.util.Calendar.DAY_OF_MONTH)
        Log.d(TAG, "Generating age proof: birth=$birthYear-$birthMonth-$birthDay  current=$currentYear-$currentMonth-$currentDay  minAge=18")

        return withTimeout(PROOF_TIMEOUT_MS) {
            suspendCancellableCoroutine { continuation ->

                // Create or reuse WebView
                if (webView == null) {
                    initWebView()
                }

                // Register callback BEFORE triggering JavaScript
                proofCallback = { result ->
                    proofCallback = null
                    if (result.isSuccess) {
                        continuation.resume(result.getOrThrow())
                    } else {
                        continuation.resumeWithException(result.exceptionOrNull()!!)
                    }
                }

                // Wait for engine ready, then call JS
                val runJs = {
                    Log.d(TAG, "Calling generateAgeProof in WebView JS")
                    webView?.evaluateJavascript(
                        "generateAgeProof($birthYear, $birthMonth, $birthDay, $currentYear, $currentMonth, $currentDay, 18);",
                        null
                    )
                }

                if (engineReady) {
                    runJs()
                } else {
                    // Wait for onEngineReady callback then run
                    pendingProofAction = { runJs() }
                }

                continuation.invokeOnCancellation {
                    proofCallback = null
                    pendingProofAction = null
                }
            }
        }
    }

    /**
     * Generate a vaccine ZK proof.
     * Proves "I hold a vaccination record for vaccine [targetVaccine]" without revealing
     * the vaccinationId or salt.
     * Must be called from the MAIN THREAD (WebView requirement).
     *
     * @param vaccinationId  Blockchain ID of the vaccination record. STAYS ON DEVICE.
     * @param vaccineName    Integer vaccine code from [VaccineCodes]. STAYS ON DEVICE.
     * @param salt           Random nonce generated at commitment creation. STAYS ON DEVICE.
     * @param commitment     Poseidon(vaccinationId, vaccineName, salt) — already on-chain.
     * @param targetVaccine  The vaccine code to prove (must equal vaccineName in circuit).
     * @return VaccineZkpProofResult — proof + [isVaccinated=1, commitment, targetVaccine]
     */
    @SuppressLint("SetJavaScriptEnabled")
    suspend fun generateVaccineProof(
        vaccinationId: Long,
        vaccineName: Int,
        salt: String,
        commitment: String,
        targetVaccine: Int
    ): VaccineZkpProofResult {
        Log.d(TAG, "Generating vaccine proof: id=$vaccinationId vaccine=$vaccineName target=$targetVaccine")

        return withTimeout(PROOF_TIMEOUT_MS) {
            suspendCancellableCoroutine { continuation ->

                if (webView == null) {
                    initWebView()
                }

                vaccineProofCallback = { result ->
                    vaccineProofCallback = null
                    if (result.isSuccess) {
                        continuation.resume(result.getOrThrow())
                    } else {
                        continuation.resumeWithException(result.exceptionOrNull()!!)
                    }
                }

                val runJs = {
                    Log.d(TAG, "Calling generateVaccineProof in WebView JS")
                    webView?.evaluateJavascript(
                        "generateVaccineProof($vaccinationId, $vaccineName, $salt, $commitment, $targetVaccine);",
                        null
                    )
                }

                if (engineReady) {
                    runJs()
                } else {
                    pendingProofAction = { runJs() }
                }

                continuation.invokeOnCancellation {
                    vaccineProofCallback = null
                    pendingProofAction = null
                }
            }
        }
    }

    /**
     * Compute poseidon(vaccinationId, vaccineCode, salt) via the JS engine.
     * Returns the decimal string commitment to register on-chain.
     * Must be called from the Main thread (WebView requirement).
     */
    suspend fun computePoseidonCommitment(
        vaccinationId: Long,
        vaccineCode: Int,
        salt: java.math.BigInteger
    ): java.math.BigInteger = kotlinx.coroutines.suspendCancellableCoroutine { continuation ->
        if (webView == null) {
            initWebView()
        }

        fun runJs() {
            poseidonCallback = { result ->
                poseidonCallback = null
                if (continuation.isActive) continuation.resumeWith(result.map { java.math.BigInteger(it) })
            }

            Log.d(TAG, "Computing Poseidon commitment via JS")
            webView?.evaluateJavascript(
                "computePoseidonHash($vaccinationId, $vaccineCode, '${salt}');",
                null
            )
        }

        if (engineReady) runJs() else pendingProofAction = { runJs() }

        continuation.invokeOnCancellation {
            poseidonCallback = null
            pendingProofAction = null
        }
    }

    /**
     * Destroy the WebView when done (call from Activity.onDestroy).
     */
    fun destroy() {
        webView?.let {
            (it.parent as? ViewGroup)?.removeView(it)
            it.destroy()
        }
        webView = null
        engineReady = false
        proofCallback = null
        vaccineProofCallback = null
        poseidonCallback = null
        pendingProofAction = null
    }

    // -------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------

    private var pendingProofAction: (() -> Unit)? = null

    @SuppressLint("SetJavaScriptEnabled")
    private fun initWebView() {
        Log.d(TAG, "Initialising ZKP WebView")

        val assetLoader = WebViewAssetLoader.Builder()
            .setDomain("localhost")
            .addPathHandler("/assets/", WebViewAssetLoader.AssetsPathHandler(context))
            .build()

        webView = WebView(context).apply {
            settings.javaScriptEnabled = true
            settings.allowFileAccess = false
            settings.domStorageEnabled = true

            addJavascriptInterface(ZkpBridge(), "ZkpBridge")

            // Capture JS console output for debugging
            webChromeClient = object : WebChromeClient() {
                override fun onConsoleMessage(msg: ConsoleMessage): Boolean {
                    Log.d("$TAG/JS", "[${msg.messageLevel()}] ${msg.message()} (${msg.sourceId()}:${msg.lineNumber()})")
                    return true
                }
            }

            webViewClient = object : WebViewClient() {
                override fun shouldInterceptRequest(
                    view: WebView,
                    request: WebResourceRequest
                ): WebResourceResponse? {
                    val response = assetLoader.shouldInterceptRequest(request.url)
                        ?: return null
                    val path = request.url.path ?: ""
                    val mime = when {
                        path.endsWith(".wasm") -> "application/wasm"
                        path.endsWith(".zkey") -> "application/octet-stream"
                        path.endsWith(".js")   -> "application/javascript"
                        else                   -> return response
                    }
                    return WebResourceResponse(mime, response.encoding, response.data)
                }

                override fun onPageFinished(view: WebView, url: String) {
                    Log.d(TAG, "WebView page loaded: $url")
                }
            }

            // *** CRITICAL: attach to window so JS executes ***
            // Add as a 1x1 invisible view to the activity's root layout
            visibility = android.view.View.INVISIBLE
            activity.addContentView(
                this,
                ViewGroup.LayoutParams(1, 1)
            )

            loadUrl("https://localhost/assets/zkp/snarkjs_wrapper.html")
        }
    }

    /**
     * JavaScript ↔ Kotlin bridge.
     * Methods annotated @JavascriptInterface are callable from JS.
     */
    private inner class ZkpBridge {

        @JavascriptInterface
        fun onEngineReady() {
            Log.d(TAG, "snarkjs engine ready in WebView")
            engineReady = true
            pendingProofAction?.let {
                webView?.post { it() }
                pendingProofAction = null
            }
        }

        @JavascriptInterface
        fun onProofReady(jsonResult: String) {
            Log.d(TAG, "Proof received from WebView (${jsonResult.length} chars)")
            try {
                val result = parseProofJson(jsonResult)
                proofCallback?.invoke(Result.success(result))
            } catch (e: Exception) {
                Log.e(TAG, "Failed to parse proof JSON", e)
                proofCallback?.invoke(Result.failure(e))
            }
        }

        @JavascriptInterface
        fun onVaccineProofReady(jsonResult: String) {
            Log.d(TAG, "Vaccine proof received from WebView (${jsonResult.length} chars)")
            try {
                val result = parseVaccineProofJson(jsonResult)
                vaccineProofCallback?.invoke(Result.success(result))
            } catch (e: Exception) {
                Log.e(TAG, "Failed to parse vaccine proof JSON", e)
                vaccineProofCallback?.invoke(Result.failure(e))
            }
        }

        @JavascriptInterface
        fun onPoseidonReady(commitment: String) {
            Log.d(TAG, "Poseidon ready: ${commitment.take(20)}...")
            poseidonCallback?.invoke(Result.success(commitment))
        }

        @JavascriptInterface
        fun onProofError(errorMessage: String) {
            Log.e(TAG, "Proof generation error: $errorMessage")
            // Route to whichever callback is active
            proofCallback?.invoke(
                Result.failure(Exception("ZKP proof failed: $errorMessage"))
            )
            vaccineProofCallback?.invoke(
                Result.failure(Exception("ZKP proof failed: $errorMessage"))
            )
            poseidonCallback?.invoke(
                Result.failure(Exception("Poseidon compute failed: $errorMessage"))
            )
        }
    }

    /**
     * Parse the JSON returned by snarkjs.groth16.fullProve into a ZkpProofResult.
     *
     * snarkjs format:
     * {
     *   "proof": {
     *     "pi_a": ["x", "y", "1"],
     *     "pi_b": [["xx","xy"], ["yx","yy"], ["1","0"]],
     *     "pi_c": ["x", "y", "1"],
     *     "protocol": "groth16",
     *     "curve": "bn128"
     *   },
     *   "publicSignals": ["1", "2026", "18"]
     * }
     */
    private fun parseVaccineProofJson(json: String): VaccineZkpProofResult {
        val root = JSONObject(json)
        val proof = root.getJSONObject("proof")
        val signals = root.getJSONArray("publicSignals")

        fun jsonArrayToList(arr: org.json.JSONArray): List<String> =
            (0 until arr.length()).map { arr.getString(it) }

        fun jsonArrayToList2D(arr: org.json.JSONArray): List<List<String>> =
            (0 until arr.length()).map { i -> jsonArrayToList(arr.getJSONArray(i)) }

        val proofA = jsonArrayToList(proof.getJSONArray("pi_a")).take(2)
        val proofB = jsonArrayToList2D(proof.getJSONArray("pi_b")).take(2)
        val proofC = jsonArrayToList(proof.getJSONArray("pi_c")).take(2)
        val publicSignals = jsonArrayToList(signals)

        val result = VaccineZkpProofResult(proofA, proofB, proofC, publicSignals)

        if (!result.isStructureValid()) {
            throw Exception("Vaccine proof structure invalid — expected 3 public signals [isVaccinated, commitment, targetVaccine]")
        }

        return result
    }

    private fun parseProofJson(json: String): ZkpProofResult {
        val root = JSONObject(json)
        val proof = root.getJSONObject("proof")
        val signals = root.getJSONArray("publicSignals")

        fun jsonArrayToList(arr: JSONArray): List<String> =
            (0 until arr.length()).map { arr.getString(it) }

        fun jsonArrayToList2D(arr: JSONArray): List<List<String>> =
            (0 until arr.length()).map { i -> jsonArrayToList(arr.getJSONArray(i)) }

        val proofA = jsonArrayToList(proof.getJSONArray("pi_a")).take(2)
        val proofB = jsonArrayToList2D(proof.getJSONArray("pi_b")).take(2)
        val proofC = jsonArrayToList(proof.getJSONArray("pi_c")).take(2)
        val publicSignals = jsonArrayToList(signals)

        val result = ZkpProofResult(proofA, proofB, proofC, publicSignals)

        if (!result.isStructureValid()) {
            throw Exception("Proof structure invalid — circuit may have different public signals")
        }

        return result
    }
}
